# Generated by Django 3.1.3 on 2021-01-28 15:05

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20210128_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', jsonfield.fields.JSONField(default={'habr': '', 'headhanter': ''})),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.city', verbose_name='Город')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.profession', verbose_name='Ключевой навык')),
            ],
            options={
                'unique_together': {('city', 'profession')},
            },
        ),
    ]
