# Generated by Django 3.1.3 on 2021-01-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Ключевой навык', 'verbose_name_plural': 'Ключевые навыки'},
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ключевой навык'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.profession', verbose_name='Ключевой навык'),
        ),
    ]
