# Generated by Django 3.1.3 on 2021-01-30 22:32

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_data',
            field=jsonfield.fields.JSONField(default={'habr': '', 'headhunter': ''}),
        ),
    ]
